### ISSUE TITLE
failed to execute

### ISSUE THREAD

**Issue by DanConwayDev** [lez/git-remote-blossom#2]
first time running `git push origin --all` after adding the remote per the readme instructions failed with:

```
fatal: 'remote-nostr' appears to be a git command, but we were not
able to execute it. Maybe git-remote-nostr is broken?
```

binary permissions:
```
-rwxr-xr-x 1 root root 1043 Jun 11 10:20 /usr/bin/git-remote-nostr
```

I'd set global git config for nostr.blossom, nostr.relay pointing at ports on localhost.

I also added nostr.nsec.

running on a fresh Debian 12 install.

**Comment by lez** [comment]
right now a dependency doesn't support python < 3.10. But I got more explicit error messages when I tried pushing the repo with python 3.9.
Can you run `git-remote-nostr` directly to see if there is a hint there?

**Comment by lez** [comment]
pushed new version, which installs to my best knowledge.
